export const trendsRu = {
  // heading is the label of the toolbar tab; pageTitle is the H1 inside the panel. They are
  // deliberately different — the nav keeps the product name, the page reads as plain Russian.
  heading: 'TRENDSWATCHING',
  pageTitle: 'Тренды',
  subtitle: 'От находки — к идее для вашего бренда',
  demoBadge: 'Демо-данные',
  demoHint:
    'Настоящих трендов в базе пока нет — это пример того, как раздел выглядит с данными. Нажмите «Обновить», чтобы собрать реальные.',
  searchPlaceholder: 'Поиск по трендам, темам, авторам или ключевым словам…',
  searchSettings: 'Настройки поиска',
  settingsRegion: 'Регион',
  regionAll: 'Все',
  regionCis: 'СНГ',
  regionEurope: 'Европа',
  regionAmerica: 'Америка',
  regionUnknown: 'Не определён',
  settingsShow: 'Показывать',
  showAll: 'Все',
  showSaved: 'Только сохранённые',
  settingsReset: 'Сбросить',
  regionNote: 'У Instagram и Threads регион определяется по языку постов, у TikTok — по стране сбора.',
  allPlatforms: 'Все площадки',
  rangeToday: 'Сегодня',
  range7d: 'За 7 дней',
  range30d: 'За 30 дней',
  sortPopular: 'По популярности',
  sortNewest: 'Сначала новые',
  sortLikes: 'По лайкам',
  loading: 'Собираем тренды…',
  error: 'Не удалось загрузить тренды.',
  empty: 'Трендов пока нет — первый сбор ещё не запускался или идёт прямо сейчас.',
  noMatches: 'Ничего не нашлось. Попробуйте другой запрос или снимите фильтры.',
  // Which metric a row shows depends on what the source actually reported: a post with no
  // like count falls back to views, and so on. Nothing here is a projection or a growth rate —
  // the collector doesn't track history, so there is no honest "+320%" to show.
  metricLikes: 'Лайков',
  metricViews: 'Просмотров',
  metricReposts: 'Репостов',
  metricComments: 'Комментариев',
  metricNone: 'В подборке',
  whyHeading: 'Почему в подборке',
  howHeading: 'Как применить',
  whyFallback: 'Пост попал в подборку по охвату и вовлечённости среди похожих авторов.',
  openOriginal: 'Открыть оригинал',
  save: 'Сохранить',
  saved: 'Сохранено',
  createScenario: 'Создать сценарий',
  toNodes: 'В ноды',
  selectHint: 'Выберите тренд слева, чтобы посмотреть детали.',
  refreshBtn: 'Обновить',
  refreshingBtn: 'Обновляем…',
  refreshError: 'Не удалось обновить — попробуйте ещё раз чуть позже.',
  close: 'Закрыть',
};

export const trendsEn: typeof trendsRu = {
  heading: 'TRENDSWATCHING',
  pageTitle: 'Trends',
  subtitle: 'From a find to an idea for your brand',
  demoBadge: 'Demo data',
  demoHint:
    'No real trends collected yet — this is what the section looks like with data. Hit Refresh to gather real ones.',
  searchPlaceholder: 'Search trends, topics, authors or keywords…',
  searchSettings: 'Search settings',
  settingsRegion: 'Region',
  regionAll: 'All',
  regionCis: 'CIS',
  regionEurope: 'Europe',
  regionAmerica: 'Americas',
  regionUnknown: 'Undetermined',
  settingsShow: 'Show',
  showAll: 'All',
  showSaved: 'Saved only',
  settingsReset: 'Reset',
  regionNote: 'For Instagram and Threads the region is inferred from post language; for TikTok it is the country it was collected from.',
  allPlatforms: 'All platforms',
  rangeToday: 'Today',
  range7d: 'Last 7 days',
  range30d: 'Last 30 days',
  sortPopular: 'By popularity',
  sortNewest: 'Newest first',
  sortLikes: 'By likes',
  loading: 'Gathering trends…',
  error: 'Could not load trends.',
  empty: 'No trends yet — the first collection run hasn’t happened, or is running right now.',
  noMatches: 'Nothing matched. Try another query or clear the filters.',
  metricLikes: 'Likes',
  metricViews: 'Views',
  metricReposts: 'Reposts',
  metricComments: 'Comments',
  metricNone: 'In the list',
  whyHeading: 'Why it’s here',
  howHeading: 'How to use it',
  whyFallback: 'This post made the list on reach and engagement among comparable authors.',
  openOriginal: 'Open original',
  save: 'Save',
  saved: 'Saved',
  createScenario: 'Create a scenario',
  toNodes: 'To canvas',
  selectHint: 'Pick a trend on the left to see the details.',
  refreshBtn: 'Refresh',
  refreshingBtn: 'Refreshing…',
  refreshError: 'Could not refresh — try again shortly.',
  close: 'Close',
};
