export const trendsRu = {
  heading: 'TRENDSWATCHING',
  updated: (date: string) => `Обновлено: ${date}`,
  allPlatforms: 'Все площадки',
  rangeToday: 'Сегодня',
  range3d: 'До 3 дней',
  range10d: 'До 10 дней',
  loading: 'Собираем тренды…',
  error: 'Не удалось загрузить тренды.',
  empty: 'Трендов пока нет — первый сбор ещё не запускался или идёт прямо сейчас.',
  appearedLabel: 'Появился',
  repostsLabel: 'Репостов',
  likesLabel: 'Лайков',
  adviceLabel: 'Совет ИИ',
  author: 'Автор',
  openSource: 'Открыть источник',
  close: 'Закрыть',
  refreshBtn: 'Обновить',
  refreshingBtn: 'Обновляем…',
  refreshError: 'Не удалось обновить — попробуйте ещё раз чуть позже.',
};
export const trendsEn: typeof trendsRu = {
  heading: 'TRENDSWATCHING',
  updated: (date: string) => `Updated: ${date}`,
  allPlatforms: 'All platforms',
  rangeToday: 'Today',
  range3d: 'Up to 3 days',
  range10d: 'Up to 10 days',
  loading: 'Gathering trends…',
  error: 'Could not load trends.',
  empty: 'No trends yet — the first collection run hasn’t happened, or is running right now.',
  appearedLabel: 'Appeared',
  repostsLabel: 'Reposts',
  likesLabel: 'Likes',
  adviceLabel: 'AI tip',
  author: 'Author',
  openSource: 'Open source',
  close: 'Close',
  refreshBtn: 'Refresh',
  refreshingBtn: 'Refreshing…',
  refreshError: 'Could not refresh — try again shortly.',
};
