export const messengerRu = {
  tabDirect: 'Личные', tabGroups: 'Группы',
  noDirect: 'Личных переписок пока нет. Откройте «Коллеги» и выберите, кому написать.',
  noGroups: 'Групп пока нет. Создайте первую — для проекта, запуска или команды.',
  today: 'Сегодня', yesterday: 'Вчера', locale: 'ru-RU',
  editName: 'Изменить имя для коллег',
  onlineSection: 'В сети', offlineSection: 'Не в сети',
  groupMembers: (total: number, online: number) => {
    const m10 = total % 10, m100 = total % 100;
    const word = m10 === 1 && m100 !== 11 ? 'участник' : m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14) ? 'участника' : 'участников';
    return online > 0 ? `${total} ${word} · ${online} в сети` : `${total} ${word}`;
  },
  bubbleLabel: 'Открыть мессенджер', title: 'Мессенджер', close: 'Закрыть',
  tabChats: 'Чаты', tabPeople: 'Коллеги',
  newDm: 'Написать', newGroup: 'Новая группа',
  searchPeople: 'Поиск коллег', online: 'В сети', offline: 'Не в сети',
  noChannels: 'Пока нет чатов. Выберите коллегу на вкладке «Коллеги».',
  noPeople: 'Пока никто из коллег не открывал мессенджер.',
  noMessages: 'Сообщений пока нет. Начните разговор.',
  loading: 'Загрузка…', error: 'Не удалось загрузить. Попробуйте ещё раз.', retry: 'Повторить',
  messagePlaceholder: 'Напишите сообщение…', send: 'Отправить',
  you: 'Вы', back: 'Назад',
  groupTitlePlaceholder: 'Название группы', selectMembers: 'Участники', create: 'Создать',
  cancel: 'Отмена', membersCount: (n: number) => `${n} участ.`,
  displayNamePrompt: 'Ваше имя для коллег', save: 'Сохранить',
  restricted: 'Мессенджер доступен только сотрудникам с почтой @mechta.kz.',
  statusIdle: 'Чилит', statusGenerating: 'Жестко генерит шедевры',
  statusCopywriting: 'Жестко пишет текста', statusEvaluating: 'Оценивает свою работу',
  stickers: 'Стикеры', gifs: 'GIF', searchGifs: 'Поиск GIF', noGifs: 'Ничего не найдено.',
  attachFile: 'Прикрепить файл', fileTooBig: 'Файл больше 25 МБ.',
  openMessenger: 'Открыть чаты', moreLabel: (n: number) => `Ещё ${n}`,
  readLabel: 'Прочитано', sentLabel: 'Отправлено', downloadFile: 'Скачать',
};
export const messengerEn: typeof messengerRu = {
  tabDirect: 'Direct', tabGroups: 'Groups',
  noDirect: 'No direct chats yet. Open "Colleagues" and pick someone to message.',
  noGroups: 'No groups yet. Create one for a project, a launch or your team.',
  today: 'Today', yesterday: 'Yesterday', locale: 'en-US',
  editName: 'Change your name for colleagues',
  onlineSection: 'Online', offlineSection: 'Offline',
  groupMembers: (total: number, online: number) =>
    `${total} member${total === 1 ? '' : 's'}${online > 0 ? ` · ${online} online` : ''}`,
  bubbleLabel: 'Open messenger', title: 'Messenger', close: 'Close',
  tabChats: 'Chats', tabPeople: 'Colleagues',
  newDm: 'Message', newGroup: 'New group',
  searchPeople: 'Search colleagues', online: 'Online', offline: 'Offline',
  noChannels: 'No chats yet. Pick a colleague on the "Colleagues" tab.',
  noPeople: 'No colleagues have opened the messenger yet.',
  noMessages: 'No messages yet. Start the conversation.',
  loading: 'Loading…', error: 'Could not load. Please retry.', retry: 'Retry',
  messagePlaceholder: 'Write a message…', send: 'Send',
  you: 'You', back: 'Back',
  groupTitlePlaceholder: 'Group name', selectMembers: 'Members', create: 'Create',
  cancel: 'Cancel', membersCount: (n: number) => `${n} member${n === 1 ? '' : 's'}`,
  displayNamePrompt: 'Your name for colleagues', save: 'Save',
  restricted: 'The messenger is only available to @mechta.kz staff.',
  statusIdle: 'Chilling', statusGenerating: 'Cranking out masterpieces',
  statusCopywriting: 'Cranking out copy', statusEvaluating: 'Reviewing their work',
  stickers: 'Stickers', gifs: 'GIF', searchGifs: 'Search GIFs', noGifs: 'Nothing found.',
  attachFile: 'Attach file', fileTooBig: 'File is larger than 25 MB.',
  openMessenger: 'Open chats', moreLabel: (n: number) => `${n} more`,
  readLabel: 'Read', sentLabel: 'Sent', downloadFile: 'Download',
};
