export const messengerRu = {
  inviteTitle: 'Пригласить соавтора',
  inviteHint: 'Введите почту, с которой человек зарегистрирован в ONEFLOW. Когда он примет приглашение, вы появитесь друг у друга в контактах.',
  invitePlaceholder: 'name@company.kz',
  inviteSend: 'Отправить приглашение',
  inviteSending: 'Отправляем…',
  inviteSent: 'Приглашение отправлено. Как только человек его примет, он появится в контактах.',
  inviteAlready: 'Этот человек уже у вас в контактах.',
  inviteAccepted: 'Он уже приглашал вас — теперь вы в контактах.',
  inviteInvalid: 'Введите корректный адрес почты.',
  invitesIncoming: 'Приглашения', invitesOutgoing: 'Ожидают ответа',
  inviteToastTitle: 'Приглашение в контакты',
  inviteToastText: (name: string) => `${name} приглашает вас в контакты`,
  accept: 'Принять', decline: 'Отклонить', cancelInvite: 'Отменить',
  inviteAcceptedToast: (name: string) => `${name} теперь в ваших контактах`,
  noContacts: 'Контактов пока нет. Пригласите соавтора по почте — после того как он примет приглашение, сможете переписываться.',
  tabDirect: 'Личные', tabGroups: 'Группы',
  noDirect: 'Личных переписок пока нет. Откройте «Контакты» и выберите, кому написать.',
  noGroups: 'Групп пока нет. Создайте первую — для проекта, запуска или команды.',
  today: 'Сегодня', yesterday: 'Вчера', locale: 'ru-RU',
  editName: 'Изменить своё имя в мессенджере',
  onlineSection: 'В сети', offlineSection: 'Не в сети',
  groupMembers: (total: number, online: number) => {
    const m10 = total % 10, m100 = total % 100;
    const word = m10 === 1 && m100 !== 11 ? 'участник' : m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14) ? 'участника' : 'участников';
    return online > 0 ? `${total} ${word} · ${online} в сети` : `${total} ${word}`;
  },
  bubbleLabel: 'Открыть мессенджер', title: 'Мессенджер', close: 'Закрыть',
  tabChats: 'Чаты', tabPeople: 'Контакты',
  newDm: 'Написать', newGroup: 'Новая группа',
  searchPeople: 'Поиск по контактам', online: 'В сети', offline: 'Не в сети',
  noChannels: 'Пока нет чатов. Выберите человека на вкладке «Контакты».',
  noPeople: 'Никого не нашлось.',
  noMessages: 'Сообщений пока нет. Начните разговор.',
  loading: 'Загрузка…', error: 'Не удалось загрузить. Попробуйте ещё раз.', retry: 'Повторить',
  messagePlaceholder: 'Напишите сообщение…', send: 'Отправить',
  you: 'Вы', back: 'Назад',
  groupTitlePlaceholder: 'Название группы', selectMembers: 'Участники', create: 'Создать',
  cancel: 'Отмена', membersCount: (n: number) => `${n} участ.`,
  displayNamePrompt: 'Ваше имя в мессенджере', save: 'Сохранить',
  restricted: 'Мессенджер доступен только сотрудникам с почтой @mechta.kz.',
  statusIdle: 'Чилит', statusGenerating: 'Жестко генерит шедевры',
  statusCopywriting: 'Жестко пишет текста', statusEvaluating: 'Оценивает свою работу',
  stickers: 'Стикеры', gifs: 'GIF', searchGifs: 'Поиск GIF', noGifs: 'Ничего не найдено.',
  attachFile: 'Прикрепить файл', fileTooBig: 'Файл больше 25 МБ.',
  openMessenger: 'Открыть чаты', moreLabel: (n: number) => `Ещё ${n}`,
  readLabel: 'Прочитано', sentLabel: 'Отправлено', downloadFile: 'Скачать',
};
export const messengerEn: typeof messengerRu = {
  inviteTitle: 'Invite a collaborator',
  inviteHint: 'Enter the email they use for ONEFLOW. Once they accept, you appear in each other\'s contacts.',
  invitePlaceholder: 'name@company.com',
  inviteSend: 'Send invite',
  inviteSending: 'Sending…',
  inviteSent: 'Invite sent. They will appear in your contacts once they accept.',
  inviteAlready: 'This person is already in your contacts.',
  inviteAccepted: 'They had already invited you — you are now contacts.',
  inviteInvalid: 'Enter a valid email address.',
  invitesIncoming: 'Invitations', invitesOutgoing: 'Awaiting reply',
  inviteToastTitle: 'Contact invitation',
  inviteToastText: (name: string) => `${name} invites you to their contacts`,
  accept: 'Accept', decline: 'Decline', cancelInvite: 'Cancel',
  inviteAcceptedToast: (name: string) => `${name} is now in your contacts`,
  noContacts: 'No contacts yet. Invite a collaborator by email — once they accept, you can message each other.',
  tabDirect: 'Direct', tabGroups: 'Groups',
  noDirect: 'No direct chats yet. Open "Contacts" and pick someone to message.',
  noGroups: 'No groups yet. Create one for a project, a launch or your team.',
  today: 'Today', yesterday: 'Yesterday', locale: 'en-US',
  editName: 'Change your name in the messenger',
  onlineSection: 'Online', offlineSection: 'Offline',
  groupMembers: (total: number, online: number) =>
    `${total} member${total === 1 ? '' : 's'}${online > 0 ? ` · ${online} online` : ''}`,
  bubbleLabel: 'Open messenger', title: 'Messenger', close: 'Close',
  tabChats: 'Chats', tabPeople: 'Contacts',
  newDm: 'Message', newGroup: 'New group',
  searchPeople: 'Search contacts', online: 'Online', offline: 'Offline',
  noChannels: 'No chats yet. Pick someone on the "Contacts" tab.',
  noPeople: 'Nobody found.',
  noMessages: 'No messages yet. Start the conversation.',
  loading: 'Loading…', error: 'Could not load. Please retry.', retry: 'Retry',
  messagePlaceholder: 'Write a message…', send: 'Send',
  you: 'You', back: 'Back',
  groupTitlePlaceholder: 'Group name', selectMembers: 'Members', create: 'Create',
  cancel: 'Cancel', membersCount: (n: number) => `${n} member${n === 1 ? '' : 's'}`,
  displayNamePrompt: 'Your name in the messenger', save: 'Save',
  restricted: 'The messenger is only available to @mechta.kz staff.',
  statusIdle: 'Chilling', statusGenerating: 'Cranking out masterpieces',
  statusCopywriting: 'Cranking out copy', statusEvaluating: 'Reviewing their work',
  stickers: 'Stickers', gifs: 'GIF', searchGifs: 'Search GIFs', noGifs: 'Nothing found.',
  attachFile: 'Attach file', fileTooBig: 'File is larger than 25 MB.',
  openMessenger: 'Open chats', moreLabel: (n: number) => `${n} more`,
  readLabel: 'Read', sentLabel: 'Sent', downloadFile: 'Download',
};
