export const messengerRu = {
  bubbleLabel: 'Открыть мессенджер', title: 'Мессенджер', close: 'Закрыть',
  tabChats: 'Чаты', tabPeople: 'Коллеги',
  newDm: 'Написать', newGroup: 'Новая группа',
  searchPeople: 'Поиск коллег', online: 'В сети', offline: 'Не в сети',
  noChannels: 'Пока нет чатов. Выберите коллегу на вкладке «Коллеги».',
  noPeople: 'Пока никто из коллег не открывал мессенджер.',
  noMessages: 'Сообщений пока нет. Начните разговор.',
  loading: 'Загрузка…', error: 'Не удалось загрузить. Попробуйте ещё раз.', retry: 'Повторить',
  messagePlaceholder: 'Напишите сообщение…', send: 'Отправить',
  you: 'Вы', back: 'Назад',
  groupTitlePlaceholder: 'Название группы', selectMembers: 'Участники', create: 'Создать',
  cancel: 'Отмена', membersCount: (n: number) => `${n} участ.`,
  displayNamePrompt: 'Ваше имя для коллег', save: 'Сохранить',
  restricted: 'Мессенджер доступен только сотрудникам с почтой @mechta.kz.',
  statusIdle: 'Чилит', statusGenerating: 'Жестко генерит шедевры',
  statusCopywriting: 'Жестко пишет текста', statusEvaluating: 'Оценивает свою работу',
  stickers: 'Стикеры', gifs: 'GIF', searchGifs: 'Поиск GIF', noGifs: 'Ничего не найдено.',
};
export const messengerEn: typeof messengerRu = {
  bubbleLabel: 'Open messenger', title: 'Messenger', close: 'Close',
  tabChats: 'Chats', tabPeople: 'Colleagues',
  newDm: 'Message', newGroup: 'New group',
  searchPeople: 'Search colleagues', online: 'Online', offline: 'Offline',
  noChannels: 'No chats yet. Pick a colleague on the "Colleagues" tab.',
  noPeople: 'No colleagues have opened the messenger yet.',
  noMessages: 'No messages yet. Start the conversation.',
  loading: 'Loading…', error: 'Could not load. Please retry.', retry: 'Retry',
  messagePlaceholder: 'Write a message…', send: 'Send',
  you: 'You', back: 'Back',
  groupTitlePlaceholder: 'Group name', selectMembers: 'Members', create: 'Create',
  cancel: 'Cancel', membersCount: (n: number) => `${n} member${n === 1 ? '' : 's'}`,
  displayNamePrompt: 'Your name for colleagues', save: 'Save',
  restricted: 'The messenger is only available to @mechta.kz staff.',
  statusIdle: 'Chilling', statusGenerating: 'Cranking out masterpieces',
  statusCopywriting: 'Cranking out copy', statusEvaluating: 'Reviewing their work',
  stickers: 'Stickers', gifs: 'GIF', searchGifs: 'Search GIFs', noGifs: 'Nothing found.',
};
