import { call, done, fake, load, ok, reset, token } from './harness.ts';
const A = token('user-a');
fake.users['user-a'] = { id: 'aaaaaaaa-0000-0000-0000-000000000001', email: 'a@example.com', email_confirmed_at: '2026-01-01T00:00:00Z' };
const CH = '11111111-2222-3333-4444-555555555555';
fake.tables['messenger_members'] = (_m, url) => (url.searchParams.get('channel_id') === `eq.${CH}` ? [{ email: 'a@example.com' }] : []);
fake.tables['messenger_messages'] = (m, _u, body: any) => (m === 'POST' ? [{ id: 'm1', sender_email: 'a@example.com', body: body?.body ?? '', created_at: 'now', kind: body?.kind, media_url: body?.media_url ?? null }] : []);
let limiter = 0;
fake.rpc['rate_limit_hit'] = () => limiter;
await load('../../../supabase/functions/messenger-send-message/index.ts');
const posts = () => fake.calls.filter((c) => c.name === 'POST messenger_messages').length;
reset();
let r = await call('messenger-send-message', { channelId: CH, kind: 'gif', mediaUrl: 'https://evil.example/pixel.gif' }, { token: A });
ok(r.status === 400 && posts() === 0, 'GIF from a non-GIPHY host refused (no tracking pixels)');
reset();
r = await call('messenger-send-message', { channelId: CH, kind: 'gif', mediaUrl: 'https://media2.giphy.com/media/x/giphy.gif' }, { token: A });
ok(r.status === 200 && posts() === 1, 'GIPHY GIF accepted');
reset();
r = await call('messenger-send-message', { channelId: '99999999-2222-3333-4444-555555555555', text: 'hi' }, { token: A });
ok(r.status === 403 && posts() === 0, 'cannot post into a chat you are not a member of');
reset();
limiter = 12;
r = await call('messenger-send-message', { channelId: CH, text: 'hi' }, { token: A });
ok(r.status === 429 && posts() === 0, 'message rate limit → 429');
done('messenger-send-message');
